FROM    node:20-alpine

RUN npm install -g pnpm

WORKDIR /app

ARG DATABASE_URL
ENV DATABASE_URL=${DATABASE_URL}

COPY    ./package.json  ./package.json
COPY    ./pnpm-lock.yaml    ./pnpm-lock.yaml
COPY    ./packages  ./packages
COPY    ./turbo.json    ./turbo.json
COPY    ./pnpm-workspace.yaml ./pnpm-workspace.yaml

RUN     pnpm install

COPY    ./apps/web  ./apps/web

RUN     pnpm run prisma:generate

EXPOSE 3001

CMD ["pnpm", "run", "start:web"]

# docker build -build-arg DATABASE_URL="postgres" -t todo-app-backend -f ./docker/Dockerfile/frontend .